export enum HashAlgorithm {
	CADESCOM_HASH_ALGORITHM_CP_GOST_3411 = 100,
	CADESCOM_HASH_ALGORITHM_MD2 = 1,
	CADESCOM_HASH_ALGORITHM_MD4 = 2,
	CADESCOM_HASH_ALGORITHM_MD5 = 3,
	CADESCOM_HASH_ALGORITHM_SHA_256 = 4,
	CADESCOM_HASH_ALGORITHM_SHA_384 = 5,
	CADESCOM_HASH_ALGORITHM_SHA_512 = 6,
	CADESCOM_HASH_ALGORITHM_SHA1 = 0
}
